#line 2 "ext/attn/asn/ext_parser/lexer.c"
#line 32 "ext/attn/asn/ext_parser/ext_parser.l"

    #include "ext_common.h"




#line 10 "ext/attn/asn/ext_parser/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[574] =
    {   0,
        0,    0,    0,    0,  116,  114,  103,  103,   14,   19,
      114,    7,    8,   11,  114,  114,   20,  104,  104,   17,
       18,   15,   16,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,    5,    6,   13,  109,    9,   12,   10,
        3,  115,    3,    0,    0,    0,    4,  105,   24,    1,
        0,  104,    0,    0,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,    0,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,   42,

      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,   21,
       22,  109,    2,  112,  111,    0,    4,    0,  105,   25,
      107,  106,   23,  110,   46,  110,  110,  110,   37,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,   28,
      110,  110,  110,  110,  110,  110,  110,  110,    0,  113,
        0,  110,  110,  110,  110,  110,  110,  110,   48,   47,
      110,  110,  110,  110,  110,  110,  110,   62,  110,  110,
      110,  110,  110,  110,  110,   29,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  108,  110,

      110,  110,  110,  110,  110,  110,  110,  110,  110,   58,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
       89,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,   30,  110,  110,  110,  110,  110,  110,
      110,  110,  110,   34,  110,  110,  110,   39,  110,  110,
       96,   69,   49,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,   27,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,   50,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,   35,  110,  110,

      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,   45,  110,  110,  110,  110,  110,   93,  110,  110,
      110,  110,  110,   40,  110,  110,  110,  110,  110,  110,
      110,  110,   43,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,   65,  110,  110,  110,  110,  110,  110,  110,
      110,  110,   38,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,   31,  110,  110,  110,  110,   52,
      110,  110,  110,  110,  110,   98,  110,  110,  110,  110,
      110,  110,  110,  101,   99,  110,  110,   32,  110,  110,

      110,  110,  110,  110,   94,  110,   92,   56,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,   87,  110,  110,   60,   61,
      110,   54,  110,   63,  110,  110,  110,  110,   53,   88,
      110,  110,  110,  110,  110,  110,   51,  110,  110,  110,
       41,   95,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  102,   74,   36,   90,   59,  110,  110,  110,  110,
      110,   77,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,   82,  110,  110,   57,  110,  110,  110,  110,
      110,   91,  110,   33,  110,  110,  110,   66,  110,  110,

      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
       84,  110,  110,  110,   55,   26,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,   70,
      110,  110,  110,  110,  110,  110,  110,   97,   44,   78,
      110,   73,  110,  110,  110,   67,   68,  110,  110,  110,
      110,  100,   75,   76,  110,   79,   71,  110,  110,   81,
      110,  110,   86,   72,  110,  110,  110,   85,   80,  110,
       83,   64,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,    1,   11,   12,   13,   14,   15,   16,   17,
       17,   18,   19,   20,   17,   21,   17,   22,   23,   24,
       25,   26,    1,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   37,   49,   50,   51,
       52,   53,   54,   55,   56,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   66,   66,   67,   68,   69,
       70,   71,   66,   72,   73,   74,   75,   76,   66,   77,
       66,   66,   78,   79,   80,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[81] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    1,
        1,    4,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1,    4,    5,    5,    5,    5,
        5,    5,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[581] =
    {   0,
        0,    0,   78,   79,  695,  696,  696,  696,  696,  696,
       76,  696,  696,  696,   78,  681,  683,   87,   96,  670,
      696,  696,  696,   82,   87,   52,   92,   91,   57,   60,
      685,  106,    0,  656,  100,   96,  120,  117,  658,  107,
      130,  114,  623,  635,  632,  696,    0,  696,  696,  696,
      696,  696,  671,  135,  151,  677,    0,  160,  670,  696,
      177,  186,    0,  657,    0,  636,  642,  637,  632,  644,
      630,  633,  633,  129,  145,  627,  640,  627,  642,  170,
      179,  631,  627,  598,  609,   81,  646,  633,  621,  181,
      621,  655,  611,  619,  612,  619,  588,  619,  608,    0,

      607,  606,  603,  603,  137,  584,  182,  144,  597,  603,
      630,  612,  605,  596,  575,  606,  608,  574,  151,  696,
      696,    0,  696,  696,  696,  604,    0,  213,  222,  696,
      229,    0,  696,  606,    0,  598,  594,  599,    0,  588,
      594,  587,  595,  587,  582,  596,  187,  599,  594,    0,
      585,  592,  174,  591,  576,  581,  558,  547,  135,  696,
      614,  571,  575,  175,  576,  567,  581,  591,    0,  563,
      597,  570,  546,  575,  574,  569,  557,    0,  557,  556,
      552,  530,  560,  570,  549,  549,  563,  558,  547,  546,
      559,  558,  527,  210,  566,  510,  524,  519,  244,  543,

      547,  542,  540,  505,  547,  550,  547,  534,  547,  561,
      525,  531,  524,  539,  537,  525,  531,  521,  142,  533,
        0,  491,  498,  487,  514,  524,  514,  510,  512,  222,
      537,  509,  526,    0,  480,  522,  504,  508,  517,  535,
      515,  518,  470,    0,  497,  511,  506,    0,  500,  465,
        0,  526,    0,  463,  496,  504,  489,  472,  462,  473,
      484,  500,  501,    0,  455,  499,  496,  493,  483,  487,
      475,  482,  484,  483,  487,  472,  469,  485,  467,  467,
      471,    0,  453,  444,  436,  472,  223,  460,  475,  457,
      472,  457,  481,  488,  487,  433,  451,    0,  456,  451,

      459,  453,  446,  434,  455,  449,  448,  454,  414,  444,
      423,    0,  439,  408,  409,  406,  412,    0,  451,  431,
      411,  435,  428,    0,  442,  432,  436,  424,  423,  427,
      436,  439,    0,  430,  419,  428,  435,  394,  401,  394,
      426,  422,  426,  410,  423,  424,  408,  420,  405,  414,
      408,  388,    0,  419,  405,  404,  397,  411,  383,  392,
      410,  405,    0,  372,  404,  358,  389,  361,  359,  370,
      369,  383,  393,  358,    0,  395,  385,  379,  384,    0,
      387,  381,  390,  373,  372,    0,  389,  378,  370,  369,
      344,  377,  365,    0,    0,  365,  363,    0,  379,  333,

      366,  358,  359,  365,    0,  370,    0,    0,  334,  369,
      368,  353,  328,  384,  350,  367,  328,  335,  314,  345,
      354,  359,  324,  342,  339,    0,  353,  342,    0,    0,
      351,    0,  346,    0,  306,  305,  315,  346,    0,    0,
      341,  329,  302,  341,  333,  297,    0,  335,  308,  356,
        0,    0,  304,  336,  291,  326,  294,  295,  316,  286,
      318,    0,    0,    0,  313,    0,  317,  326,  317,  282,
      281,    0,  308,  310,  315,  284,  313,  319,  274,  305,
      299,  232,    0,  316,  270,    0,  278,  295,  265,  266,
      297,    0,  291,    0,  300,  269,  268,    0,  292,  290,

      261,  289,  297,  262,  291,  251,  280,  288,  272,  256,
        0,  246,  247,  253,    0,    0,  271,  247,  246,  269,
      273,  249,  276,  266,  240,  262,  235,  271,  275,    0,
      235,  231,  237,  232,  250,  236,  235,    0,    0,    0,
      251,    0,  233,  237,  215,    0,  260,  208,  205,  200,
      205,    0,    0,    0,  207,    0,    0,  187,  218,    0,
      167,  160,    0,    0,  156,  174,   96,    0,    0,   90,
        0,    0,  696,  273,  276,  278,  280,  285,   80,  290
    } ;

static yyconst flex_int16_t yy_def[581] =
    {   0,
      573,    1,  574,  574,  573,  573,  573,  573,  573,  573,
      575,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  573,  573,  573,  577,  573,  573,  573,
      573,  573,  573,  573,  575,  575,  578,  573,  573,  573,
      573,  573,  579,  573,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  580,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  573,
      573,  577,  573,  573,  573,  573,  578,  573,  573,  573,
      573,  579,  573,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  580,  573,
      580,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  573,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,    0,  573,  573,  573,  573,  573,  573,  573
    } ;

static yyconst flex_int16_t yy_nxt[777] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,    6,
       14,   15,   16,   17,   18,   19,   19,   19,   19,   19,
       19,   20,   21,   22,    6,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   33,   34,   35,   36,
       37,   38,   33,   39,   40,   41,   42,   43,   33,   33,
       33,   44,    6,   45,   46,    6,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   48,   49,   50,
       52,   52,   54,   82,  132,   74,  160,   53,   53,   57,
       55,   55,   75,   58,   58,   58,   58,   58,   58,   61,

       83,   62,   62,   62,   62,   62,   62,   62,   61,   66,
       62,   62,   62,   62,   62,   62,   62,   70,   76,   67,
       84,   71,   77,   68,  572,   72,   93,   73,   69,   79,
       80,   85,   87,  161,   94,   88,   95,  108,   78,   81,
      160,  109,   96,  102,   89,   90,  103,   98,   99,  111,
       91,  100,  110,  116,  104,  142,  112,   54,  571,  117,
      105,  101,  124,   63,  113,   55,   55,  180,  125,  143,
       97,  181,  128,  114,  129,  129,  129,  129,  129,  129,
      129,  280,  118,  144,  145,  281,  185,  161,  106,  186,
      115,  131,  131,  131,  131,  131,  131,  131,   61,  150,

       62,   62,   62,   62,   62,   62,   62,  152,  183,  165,
      197,  217,  226,  211,  218,  227,  151,  570,  569,  184,
      153,  212,  568,  198,  154,  166,  167,  199,  199,  199,
      199,  199,  199,  199,  128,  567,  129,  129,  129,  129,
      129,  129,  129,  131,  131,  131,  131,  131,  131,  131,
      255,  342,  566,  343,  291,  565,  564,  256,  199,  199,
      199,  199,  199,  199,  199,  292,  507,  563,  562,  561,
      560,  559,  508,   51,   51,   51,   51,   51,   56,  558,
       56,   65,   65,  122,  122,  127,  557,  127,  127,  127,
      159,  159,  159,  159,  159,  556,  555,  554,  553,  552,

      551,  550,  549,  548,  547,  546,  545,  544,  543,  542,
      541,  540,  539,  538,  537,  536,  535,  534,  533,  532,
      531,  530,  529,  528,  527,  526,  525,  524,  523,  522,
      521,  520,  519,  518,  517,  516,  515,  514,  513,  512,
      511,  510,  509,  506,  505,  504,  503,  502,  501,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  470,
      469,  468,  467,  466,  465,  464,  463,  462,  461,  460,
      459,  458,  457,  456,  455,  454,  453,  452,  451,  450,

      449,  448,  447,  446,  445,  444,  443,  442,  441,  440,
      439,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,

      349,  348,  347,  346,  345,  344,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,

      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  225,  224,  573,  223,  222,  221,
      220,  219,  216,  215,  214,  213,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  125,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  182,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
       86,  168,  164,  163,  162,  158,  157,  156,  155,  149,
      148,  147,  146,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  130,  126,  123,  121,  120,  119,  107,   92,
       86,   64,   60,   59,  573,    5,  573,  573,  573,  573,

      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573
    } ;

static yyconst flex_int16_t yy_chk[777] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,   11,   29,  579,   26,   86,    3,    4,   15,
       11,   11,   26,   15,   15,   15,   15,   15,   15,   18,

       29,   18,   18,   18,   18,   18,   18,   18,   19,   24,
       19,   19,   19,   19,   19,   19,   19,   25,   27,   24,
       30,   25,   27,   24,  570,   25,   35,   25,   24,   28,
       28,   30,   32,   86,   35,   32,   36,   40,   27,   28,
      159,   40,   36,   38,   32,   32,   38,   37,   37,   41,
       32,   37,   40,   42,   38,   74,   41,   55,  567,   42,
       38,   37,   54,   18,   41,   55,   55,  105,   54,   74,
       36,  105,   58,   41,   58,   58,   58,   58,   58,   58,
       58,  219,   42,   75,   75,  219,  108,  159,   38,  108,
       41,   61,   61,   61,   61,   61,   61,   61,   62,   80,

       62,   62,   62,   62,   62,   62,   62,   81,  107,   90,
      119,  153,  164,  147,  153,  164,   80,  566,  565,  107,
       81,  147,  562,  119,   81,   90,   90,  128,  128,  128,
      128,  128,  128,  128,  129,  561,  129,  129,  129,  129,
      129,  129,  129,  131,  131,  131,  131,  131,  131,  131,
      194,  287,  559,  287,  230,  558,  555,  194,  199,  199,
      199,  199,  199,  199,  199,  230,  482,  551,  550,  549,
      548,  547,  482,  574,  574,  574,  574,  574,  575,  545,
      575,  576,  576,  577,  577,  578,  544,  578,  578,  578,
      580,  580,  580,  580,  580,  543,  541,  537,  536,  535,

      534,  533,  532,  531,  529,  528,  527,  526,  525,  524,
      523,  522,  521,  520,  519,  518,  517,  514,  513,  512,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  497,  496,  495,  493,  491,  490,  489,  488,
      487,  485,  484,  481,  480,  479,  478,  477,  476,  475,
      474,  473,  471,  470,  469,  468,  467,  465,  461,  460,
      459,  458,  457,  456,  455,  454,  453,  450,  449,  448,
      446,  445,  444,  443,  442,  441,  438,  437,  436,  435,
      433,  431,  428,  427,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,

      409,  406,  404,  403,  402,  401,  400,  399,  397,  396,
      393,  392,  391,  390,  389,  388,  387,  385,  384,  383,
      382,  381,  379,  378,  377,  376,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  332,  331,  330,  329,  328,
      327,  326,  325,  323,  322,  321,  320,  319,  317,  316,
      315,  314,  313,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  297,  296,  295,  294,

      293,  292,  291,  290,  289,  288,  286,  285,  284,  283,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  252,  250,  249,
      247,  246,  245,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  233,  232,  231,  229,  228,  227,  226,  225,
      224,  223,  222,  220,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  198,  197,  196,  195,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,

      180,  179,  177,  176,  175,  174,  173,  172,  171,  170,
      168,  167,  166,  165,  163,  162,  161,  158,  157,  156,
      155,  154,  152,  151,  149,  148,  146,  145,  144,  143,
      142,  141,  140,  138,  137,  136,  134,  126,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  106,  104,
      103,  102,  101,   99,   98,   97,   96,   95,   94,   93,
       92,   91,   89,   88,   87,   85,   84,   83,   82,   79,
       78,   77,   76,   73,   72,   71,   70,   69,   68,   67,
       66,   64,   59,   56,   53,   45,   44,   43,   39,   34,
       31,   20,   17,   16,    5,  573,  573,  573,  573,  573,

      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "ext/attn/asn/ext_parser/ext_parser.l"
/* Flex Configuration */
#line 3 "ext/attn/asn/ext_parser/ext_parser.l"

/* includes ***********************************************************/

#include <float.h>
#include <ruby.h>
#include "parser.h"

/* static prototypes **************************************************/

/**
 * - Inserted into lexer as part of the YY_USER_ACTION macro
 * - 
 * 
 * @param[in] loc pointer to Bison location record
 * @param[in] text
 * @param[in] textLen length of text in bytes
 *
 * */
static void updateLocation(YYLTYPE *loc, const char *text, int textLen);

/* macros *************************************************************/

#define YY_USER_ACTION updateLocation(yylloc, yytext, yyleng);

/* generated **********************************************************/


#define YY_NO_INPUT 1

#line 839 "ext/attn/asn/ext_parser/lexer.c"

#define INITIAL 0
#define BLOCK_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *yyget_lloc (yyscan_t yyscanner );
    
        void yyset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 45 "ext/attn/asn/ext_parser/ext_parser.l"


#line 1087 "ext/attn/asn/ext_parser/lexer.c"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 574 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 696 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "ext/attn/asn/ext_parser/ext_parser.l"
{ BEGIN(BLOCK_COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "ext/attn/asn/ext_parser/ext_parser.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "ext/attn/asn/ext_parser/ext_parser.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "ext/attn/asn/ext_parser/ext_parser.l"
{ /* skip comments */ }
	YY_BREAK
case 5:
#line 54 "ext/attn/asn/ext_parser/ext_parser.l"
case 6:
#line 55 "ext/attn/asn/ext_parser/ext_parser.l"
case 7:
#line 56 "ext/attn/asn/ext_parser/ext_parser.l"
case 8:
#line 57 "ext/attn/asn/ext_parser/ext_parser.l"
case 9:
#line 58 "ext/attn/asn/ext_parser/ext_parser.l"
case 10:
#line 59 "ext/attn/asn/ext_parser/ext_parser.l"
case 11:
#line 60 "ext/attn/asn/ext_parser/ext_parser.l"
case 12:
#line 61 "ext/attn/asn/ext_parser/ext_parser.l"
case 13:
#line 62 "ext/attn/asn/ext_parser/ext_parser.l"
case 14:
#line 63 "ext/attn/asn/ext_parser/ext_parser.l"
case 15:
#line 64 "ext/attn/asn/ext_parser/ext_parser.l"
case 16:
#line 65 "ext/attn/asn/ext_parser/ext_parser.l"
case 17:
#line 66 "ext/attn/asn/ext_parser/ext_parser.l"
case 18:
#line 67 "ext/attn/asn/ext_parser/ext_parser.l"
case 19:
#line 68 "ext/attn/asn/ext_parser/ext_parser.l"
case 20:
YY_RULE_SETUP
#line 68 "ext/attn/asn/ext_parser/ext_parser.l"
{ return *yytext; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_LVERSION; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = Qnil; return TOK_RVERSION; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_ASSIGN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_RANGE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_ELLIPSES; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_DEFINITIONS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_BEGIN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_END; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_SET; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = Qnil; return TOK_NULL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_BOOLEAN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_INTEGER; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_ENUMERATED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_REAL; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_OCTET; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 87 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_CHARACTER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 88 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_BIT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_STRING; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_SIZE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 91 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_CHOICE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 92 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_SEQUENCE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 93 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_OF; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_EXCEPT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_INTERSECTION; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 96 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_UNION; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 97 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_ALL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 98 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_MIN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 99 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_MAX; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 100 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = Qtrue; return TOK_TRUE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 101 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = Qfalse; return TOK_FALSE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 102 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_OPTIONAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 103 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_DEFAULT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 104 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_IMPLICIT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 105 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_EXPLICIT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 106 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_APPLICATION; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 107 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_PRIVATE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 108 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_UNIVERSAL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 110 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_DATE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 111 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_DATE_TIME; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_DURATION; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_EMBEDDED; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_PDV; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_EXTERNAL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_RELATIVE_OID_IRI; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 117 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_OBJECT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 118 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_IDENTIFIER; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_RELATIVE_IRI; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_RELATIVE_OID; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 121 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_TIME; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_TIME_OF_DAY; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 124 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = rb_float_new(INFINITY); return TOK_PLUS_INFINITY; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 125 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = rb_float_new(-INFINITY); return TOK_MINUS_INFINITY; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = rb_float_new(NAN); return TOK_NOT_A_NUMBER; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 128 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_BMPString; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 129 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_GeneralString; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 130 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_GraphicString; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 131 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_IA5String; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 132 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_ISO646String; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 133 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_NumericString; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 134 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_PrintableString; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 135 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_TeletexString; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 136 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_T61String; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 137 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_UniversalString; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 138 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_UTF8String; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 139 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_VideotexString; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 140 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_VisibleString; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 142 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_CONTAINS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 143 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_INCLUDES; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 144 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_FROM; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 145 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_COMPONENT; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 146 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_COMPONENTS; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 147 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_PRESENT; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 148 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_ABSENT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 149 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_PATTERN; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 150 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_SETTINGS; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 151 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_TAGS; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 152 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_INSTRUCTIONS; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 153 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_EXPORTS; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 154 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_IMPORTS; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 155 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_EXTENSIBILITY; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 156 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_IMPLIED; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 157 "ext/attn/asn/ext_parser/ext_parser.l"
{ return TOK_AUTOMATIC; }
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 159 "ext/attn/asn/ext_parser/ext_parser.l"
;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 161 "ext/attn/asn/ext_parser/ext_parser.l"
{ unsigned int tmp = 0; sscanf(yytext, "%u", &tmp); *yylval = UINT2NUM(tmp); return TOK_POSINT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 162 "ext/attn/asn/ext_parser/ext_parser.l"
{ int tmp = 0; sscanf(yytext, "%i", &tmp); *yylval = INT2NUM(tmp); return TOK_NEGINT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 163 "ext/attn/asn/ext_parser/ext_parser.l"
{ unsigned int tmp = 0; sscanf(yytext, "%x", &tmp); *yylval = UINT2NUM(tmp); return TOK_HEXINT; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 164 "ext/attn/asn/ext_parser/ext_parser.l"
{ float tmp = 0; sscanf(yytext, "%f", &tmp); *yylval = rb_float_new(tmp); return TOK_POSREAL; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 165 "ext/attn/asn/ext_parser/ext_parser.l"
{ float tmp = 0; sscanf(yytext, "%f", &tmp); *yylval = rb_float_new(tmp); return TOK_NEGREAL; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 167 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = rb_str_new(yytext, yyleng); return TOK_ID; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 169 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = rb_str_new(yytext, yyleng); return TOK_TYPEREF; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 171 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = rb_str_new(yytext, yyleng); return TOK_HSTRING; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 172 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = rb_str_new(yytext, yyleng); return TOK_BSTRING; }
	YY_BREAK
case 113:
/* rule 113 can match eol */
YY_RULE_SETUP
#line 174 "ext/attn/asn/ext_parser/ext_parser.l"
{ *yylval = rb_str_new(yytext, yyleng); return TOK_CSTRING; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 176 "ext/attn/asn/ext_parser/ext_parser.l"
;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 178 "ext/attn/asn/ext_parser/ext_parser.l"
ECHO;
	YY_BREAK
#line 1706 "ext/attn/asn/ext_parser/lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BLOCK_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 574 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 574 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 573);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 178 "ext/attn/asn/ext_parser/ext_parser.l"



/* static functions ***************************************************/

static void updateLocation(YYLTYPE *loc, const char *text, int textLen)
{
    int i;

    loc->first_line = loc->last_line;
    loc->first_column = loc->last_column;

    for(i=0; i < textLen; i++){

        if(text[i] == '\n'){
        
            loc->last_line++;
            loc->last_column = 0;
        }
        else{
        
            loc->last_column++;
        }
    }
}

